# Generated by Django 4.2.3 on 2023-07-04 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import final_project.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customregisteruser_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelManagers(
            name='customregisteruser',
            managers=[
                ('objects', final_project.account.models.AppUserManager()),
            ],
        ),
    ]
