# Generated by Django 4.2.3 on 2023-07-05 20:16

import django.core.validators
from django.db import migrations, models
import final_project.account.validators


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_alter_customregisteruser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customregisteruser',
            options={'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customregisteruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), final_project.account.validators.validate_only_alphabetic]),
        ),
        migrations.AlterField(
            model_name='customregisteruser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), final_project.account.validators.validate_only_alphabetic]),
        ),
    ]
