# Generated by Django 4.2.3 on 2023-08-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customregisteruser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customregisteruser',
            options={'verbose_name': 'Потребители', 'verbose_name_plural': 'Потребители'},
        ),
    ]
