# Generated by Django 4.2.3 on 2023-08-11 16:19

import django.core.validators
from django.db import migrations, models
import final_project.account.validators


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customregisteruser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customregisteruser',
            name='first_name',
            field=models.CharField(blank=True, default='Dimitur', max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), final_project.account.validators.validate_only_alphabetic]),
        ),
        migrations.AlterField(
            model_name='customregisteruser',
            name='last_name',
            field=models.CharField(blank=True, default='Stoyanov', max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), final_project.account.validators.validate_only_alphabetic]),
        ),
    ]
