# Generated by Django 4.2.3 on 2023-07-20 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0019_rename_attached_user_hotels_created_by_user_and_more'),
        ('commons', '0004_alter_comments_hotel_alter_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotels'),
        ),
    ]
