# Generated by Django 4.2.3 on 2023-07-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0005_alter_comments_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='description',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
