# Generated by Django 4.2.3 on 2023-07-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0006_alter_comments_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
