# Generated by Django 4.2.3 on 2023-07-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0007_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
