# Generated by Django 4.2.3 on 2023-08-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0008_delete_search'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Коментари', 'verbose_name_plural': 'Коментари'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакти', 'verbose_name_plural': 'Контакти'},
        ),
    ]
