# Generated by Django 4.2.3 on 2023-08-07 19:58

import django.core.validators
from django.db import migrations, models
import final_project.account.validators


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0009_alter_comments_options_alter_contact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.MinLengthValidator(2), final_project.account.validators.validate_only_alphabetic]),
            preserve_default=False,
        ),
    ]
