# Generated by Django 4.2.3 on 2023-07-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_hotels_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='picture',
        ),
        migrations.AddField(
            model_name='hotels',
            name='hotel_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/hotels/'),
        ),
    ]
