# Generated by Django 4.2.3 on 2023-07-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_hotels_hotel_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('choices', models.CharField(choices=[('All inclusive', 'All inclusive'), ('Not all inclusive', 'Not all inclusive')], max_length=20)),
            ],
        ),
    ]
