# Generated by Django 4.2.3 on 2023-07-09 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0007_registrationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='attached_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reservation', to=settings.AUTH_USER_MODEL),
        ),
    ]
