# Generated by Django 4.2.3 on 2023-07-10 08:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0008_registrationmodel_attached_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationModel',
            new_name='ReservationModel',
        ),
    ]
