# Generated by Django 4.2.3 on 2023-07-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_rename_registrationmodel_reservationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
