# Generated by Django 4.2.3 on 2023-07-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_reservationmodel_final_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationmodel',
            old_name='final_price',
            new_name='total_price',
        ),
    ]
