# Generated by Django 4.2.3 on 2023-07-10 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0011_rename_final_price_reservationmodel_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='attached_hotel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reservation_hotel', to='hotels.hotels'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='attached_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL),
        ),
    ]
