# Generated by Django 4.2.3 on 2023-07-18 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0014_alter_reservationmodel_attached_hotel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/hotels/')),
            ],
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='hotel_picture',
        ),
        migrations.AlterField(
            model_name='hotels',
            name='reserve_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='attached_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotels'),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='attached_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotels',
            name='hotel_picture',
            field=models.ManyToManyField(to='hotels.picture'),
        ),
    ]
