# Generated by Django 4.2.3 on 2023-07-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_picture_remove_hotels_hotel_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='hotel_picture',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.AddField(
            model_name='hotels',
            name='hotel_picture',
            field=models.ImageField(default='', upload_to='images/hotels/'),
            preserve_default=False,
        ),
    ]
