# Generated by Django 4.2.3 on 2023-07-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_remove_hotels_hotel_picture_delete_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='days',
            field=models.PositiveIntegerField(),
        ),
    ]
