# Generated by Django 4.2.3 on 2023-07-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0018_rename_attached_user_reservationmodel_created_by_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='attached_user',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='reservationmodel',
            old_name='created_by_user',
            new_name='attached_user',
        ),
    ]
