# Generated by Django 4.2.3 on 2023-08-01 11:15

from django.db import migrations, models
import final_project.hotels.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0020_alter_reservationmodel_attached_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='hotel_name',
            field=models.CharField(max_length=30, unique=True, validators=[final_project.hotels.validators.hotel_name_validators]),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='location',
            field=models.CharField(max_length=30, validators=[final_project.hotels.validators.location_name_validators]),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='price',
            field=models.FloatField(),
        ),
    ]
